name: Semgrep Scan and Upload to DefectDojo

on: [push, pull_request]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config=auto --json --output=semgrep-results.json

      - name: Upload Semgrep Results to DefectDojo
        env:
          DD_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DD_HOST: ${{ secrets.DEFECTDOJO_HOST }}
          DD_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
        run: |
          curl -X POST "$DD_HOST/api/v2/import-scan/" \
            -H "Authorization: Token $DD_API_KEY" \
            -F "scan_type=Semgrep JSON Report" \
            -F "file=@semgrep-results.json" \
            -F "engagement=$DD_ENGAGEMENT_ID" \
            -F "minimum_severity=Low" \
            -F "active=true" \
            -F "verified=true"
